version: "3.2"
services:

  rabbit:
    image: rabbitmq:3.7-management
#    build:
#      context: rabbitmq-server
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_DEFAULT_VHOST

  file_watch:
    build:
      context: file_watch
    user: observer:observer
    environment:
      - CELERY_BACKEND_URL
      - CELERY_BROKER_URL
      - DATA_DIRECTORY
    volumes:
      - type: bind
        source: /pipeline
        target: /app/pipeline
    depends_on:
      - rabbit
    restart: always

  db:
    image: mongo
#    volumes:
#      - ./data:/data/db
    ports:
      - "27017:27017"
  # enable authorization access

  api:
    build:
      context: api
    hostname: api
    ports:
      - "4000:8080"
    depends_on:
      - rabbit
    restart: always
    links:
      - db

  web:
    build:
      context: web
    ports:
      - "3000:8080"
    depends_on:
      - rabbit
    restart: always
    links:
      - api