version: "3.2"
services:

  rabbit:
    image: rabbitmq:3.6-management
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"

  file_watch:
    build:
      context: file_watch
    user: observer:observer
    environment:
      - CELERY_BROKER_URL=amqp://guest:guest@rabbit
      - DATA_DIRECTORY=/app/pipeline/data
    volumes:
      - type: bind
        source: /pipeline
        target: /app/pipeline
    depends_on:
      - rabbit

  web_app:
    build:
      context: web_app
    ports:
      - "4000:4000"

#  worker:
#    build:
#      context: worker
#    depends_on:
#      - rabbit
