version: "3.2"
services:

  rabbit:
    build:
      context: rabbitmq-server
    hostname: "rabbit"
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_DEFAULT_VHOST

  file_watch:
    build:
      context: file_watch
    user: observer:observer
    environment:
      - CELERY_BACKEND_URL
      - CELERY_BROKER_URL
      - DATA_DIRECTORY
    volumes:
      - type: bind
        source: /pipeline
        target: /app/pipeline
    depends_on:
      - rabbit
    restart: always

#  web_app:
#    build:
#      context: web_app
#    ports:
#      - "4000:4000"
#    depends_on:
#      - rabbit
#    restart: always

  node_app:
    build:
      context: nodejs_app
    ports:
      - "4000:8080"
    depends_on:
      - rabbit
    restart: always

#  worker:
#    build:
#      context: worker
#    depends_on:
#      - rabbit

  publisher:
    build:
      context: publisher
    depends_on:
      - rabbit
    restart: always


#  consumer:
#    build:
#      context: consumer
#    depends_on:
#      - rabbit
#    restart: always